#!/bin/bash

# Basics
theme="default"
style_dir="src/style"

# Override here if necessary
layout="$style_dir/layout/$theme"
borders="$style_dir/borders/$theme"
spacing="$style_dir/spacing/$theme"
symbols="$style_dir/symbols/$theme"
headers="$style_dir/headers/$theme"

style="$( \
  cat \
    "$layout"  \
    "$borders" \
    "$spacing" \
    "$symbols" \
    "$headers" \
)"

FZF_ARGS="$(          \
  echo "$style"       \
  | sed -s 's/\\/ /g' \
  | tr '\n' ' '       \
)"
fzf $FZF_ARGS

